### ISSUE TITLE
define ('WP_ADMIN', TRUE) ??

### ISSUE THREAD

**Issue by entropyfever** [rburgst/wp-graphql-wpml#21]
I think this is a bad solution and breaks a lot of stuff, like addToCart mutation of WooGraphQL plugin. The problem is on WPML (class-wpml-query-parser.php)

```
if ( /* $this->sitepress->get_wp_api()->is_admin()
		&& */ ! $this->sitepress->get_wp_api()->constant( 'DOING_AJAX' )
	) {
		return $q;
	}
```

as you see I have commented out the ```->is_admin()``` which is also a bad idea since this function is a core function of WPML but gets my job done (ex querying products with ```graphql/lang=my_lang_code```) and also not breaking ```addToCart``` mutation. No need to define ```WP_admin``` since it changes a lot of functionality as every plugin has a ```is_admin()``` call and also it might introduce security vulnerabilities.

**Comment by rburgst** [comment]
I am open for PRs.

**Comment by rburgst** [comment]
The problem is that I cannot force people to change WPML source code. I dont see a better solution at the moment than doing it that way.
My usecase is that we use wordpress as a headless CMS and therefore, it is not available to the public internet (with all the security vulnerabilities that are currently exploited, I wouldnt dare).
