### ISSUE TITLE
Fetch menus return multiple times the same item

### ISSUE THREAD

**Issue by PaulBouisset** [rburgst/wp-graphql-wpml#8]
Hi, first thanks for your great plugin!

I have an issue trying to retrieve all my menus setup in wordpress. I have three locales defined on my website (EN,FR,DE) and one menu translated in each language. 
Each translated menu has a different name (ex: Root menu, Root menu - French) but when I make a query for the menus the response is always three times the English menu. 

Do you know what could cause this? 

<img width="1121" alt="Capture d’écran 2021-02-09 à 12 44 27" src="https://user-images.githubusercontent.com/12842320/107359454-fb7fcd80-6ad4-11eb-9273-19e12ab5b5d5.png">

**Comment by rburgst** [comment]
this is related to #3 , unfortunately the ability to fetch all menu items is not completed, since WPML does a fine job of making it extremely difficult to avoid their messing around with the DB queries. For now I recommend using https://github.com/rburgst/gatsby-source-wordpress-menus for getting the menus via REST. Once I have some spare time I will continue trying to improve this plugin to get menus fully working.

**Comment by PaulBouisset** [comment]
Ok thanks for your help, I end up using a different solution for the menu

**Comment by rburgst** [comment]
this should be fixed by 3ef28d003541a0e91fbeac5db28eba7cb4c281cc, you can now get all menus items in all languages and there is now a `language` field that allows you to query which language a menu is. 
Sadly it is not yet possible to filter menu items by language.
